#!/usr/bin/env python
#coding=utf8
#author by liuhuihuang-2016-9-26
'''
需求
输入用户名密码
认证成功后显示欢迎信息
输错三次后锁定
'''
username = "parktrick"
passwd = "123456"
count = 0
while count < 3:
    user_input = input("Please input your username:")
    passwd_input = input("please input your passwd:")

    if user_input == username and passwd_input == passwd:
        print ("welcome")
        break #认证成功退出循环
    else:
        print ("username or passwd is not right,please check")
    count += 1
else:
    print("Your account is locked")




